fontsdir = @ABIWORD_DATADIR@/fonts

nobase_dist_fonts_DATA = \
README.md \
abinova-fonts.conf \
caladea/Caladea-BoldItalic.ttf \
caladea/Caladea-Bold.ttf \
caladea/Caladea-Italic.ttf \
caladea/Caladea-Regular.ttf \
caladea/OFL.txt \
carlito/Carlito-BoldItalic.ttf \
carlito/Carlito-Bold.ttf \
carlito/Carlito-Italic.ttf \
carlito/Carlito-Regular.ttf \
carlito/OFL.txt \
dejavu/DejaVuSans-BoldOblique.ttf \
dejavu/DejaVuSans-Bold.ttf \
dejavu/DejaVuSansCondensed-BoldOblique.ttf \
dejavu/DejaVuSansCondensed-Bold.ttf \
dejavu/DejaVuSansCondensed-Oblique.ttf \
dejavu/DejaVuSansCondensed.ttf \
dejavu/DejaVuSans-ExtraLight.ttf \
dejavu/DejaVuSansMono-BoldOblique.ttf \
dejavu/DejaVuSansMono-Bold.ttf \
dejavu/DejaVuSansMono-Oblique.ttf \
dejavu/DejaVuSansMono.ttf \
dejavu/DejaVuSans-Oblique.ttf \
dejavu/DejaVuSans.ttf \
dejavu/DejaVuSerif-BoldItalic.ttf \
dejavu/DejaVuSerif-Bold.ttf \
dejavu/DejaVuSerifCondensed-BoldItalic.ttf \
dejavu/DejaVuSerifCondensed-Bold.ttf \
dejavu/DejaVuSerifCondensed-Italic.ttf \
dejavu/DejaVuSerifCondensed.ttf \
dejavu/DejaVuSerif-Italic.ttf \
dejavu/DejaVuSerif.ttf \
dejavu/LICENSE \
gentium/Gentium-BoldItalic.ttf \
gentium/Gentium-Bold.ttf \
gentium/GentiumBook-BoldItalic.ttf \
gentium/GentiumBook-Bold.ttf \
gentium/GentiumBook-Italic.ttf \
gentium/GentiumBook-Regular.ttf \
gentium/Gentium-Italic.ttf \
gentium/Gentium-Regular.ttf \
gentium/OFL.txt \
intos/Intos-BoldItalic.ttf \
intos/Intos-Bold.ttf \
intos/IntosDisplay-BoldItalic.ttf \
intos/IntosDisplay-Bold.ttf \
intos/IntosDisplay-Italic.ttf \
intos/IntosDisplay-Regular.ttf \
intos/Intos-Italic.ttf \
intos/IntosNarrow-BoldItalic.ttf \
intos/IntosNarrow-Bold.ttf \
intos/IntosNarrow-Italic.ttf \
intos/IntosNarrow-Regular.ttf \
intos/Intos-Regular.ttf \
intos/Intos-SemiboldItalic.ttf \
intos/Intos-Semibold.ttf \
intos/IntosSerif-BoldItalic.ttf \
intos/IntosSerif-Bold.ttf \
intos/IntosSerif-Italic.ttf \
intos/IntosSerif-Regular.ttf \
intos/LICENSE.txt \
liberation/COPYRIGHT \
liberation/LiberationMono-BoldItalic.ttf \
liberation/LiberationMono-Bold.ttf \
liberation/LiberationMono-Italic.ttf \
liberation/LiberationMono-Regular.ttf \
liberation/LiberationSans-BoldItalic.ttf \
liberation/LiberationSans-Bold.ttf \
liberation/LiberationSans-Italic.ttf \
liberation/LiberationSansNarrow-BoldItalic.ttf \
liberation/LiberationSansNarrow-Bold.ttf \
liberation/LiberationSansNarrow-Italic.ttf \
liberation/LiberationSansNarrow-Regular.ttf \
liberation/LiberationSans-Regular.ttf \
liberation/LiberationSerif-BoldItalic.ttf \
liberation/LiberationSerif-Bold.ttf \
liberation/LiberationSerif-Italic.ttf \
liberation/LiberationSerif-Regular.ttf \
liberation/License-Narrow.txt \
libertine/COPYRIGHT \
libertine/LinBiolinum_RB.otf \
libertine/LinBiolinum_RI.otf \
libertine/LinBiolinum_R.otf \
libertine/LinLibertine_RBI.otf \
libertine/LinLibertine_RB.otf \
libertine/LinLibertine_RI.otf \
libertine/LinLibertine_R.otf \
noto/NotoSans-BoldItalic.ttf \
noto/NotoSans-Bold.ttf \
noto/NotoSans-Italic.ttf \
noto/NotoSans-Regular.ttf \
noto/NotoSerif-BoldItalic.ttf \
noto/NotoSerif-Bold.ttf \
noto/NotoSerif-Italic.ttf \
noto/NotoSerif-Regular.ttf \
noto/OFL.txt \
opensymbol/COPYRIGHT \
opensymbol/opens___.ttf \
source/LICENSE-SourceCodePro.md \
source/LICENSE-SourceSans3.md \
source/LICENSE-SourceSerif4.md \
source/SourceCodePro-BoldIt.ttf \
source/SourceCodePro-Bold.ttf \
source/SourceCodePro-It.ttf \
source/SourceCodePro-Regular.ttf \
source/SourceSans3-BoldIt.ttf \
source/SourceSans3-Bold.ttf \
source/SourceSans3-It.ttf \
source/SourceSans3-Regular.ttf \
source/SourceSerif4-BoldIt.otf \
source/SourceSerif4-Bold.otf \
source/SourceSerif4-It.otf \
source/SourceSerif4-Regular.otf
