/* -*- mode: C++; tab-width: 4; c-basic-offset: 4; -*- */

/* Abinova is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Abinova is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef FV_COVERASSETS_H
#define FV_COVERASSETS_H

#include <string.h>

/* Cover-page artwork embedded in the binary (generated by
 * tools/mkcoverart.py into fv_CoverAssets.cpp).  The Word cover
 * originals ship non-redistributable raster art (see LIC01's audit
 * notes), so these are original programmatic equivalents: feather
 * line-art for "feathered", flourish ornaments for "filgree", a
 * stylized cypress-road landscape for "integral" and a translucent
 * facet texture for "facet". */
struct FV_CoverAsset
{
	const char *          szId;   // "feathers", "filgree", ...
	const char *          szMime; // "image/png" / "image/jpeg"
	const unsigned char * pData;
	unsigned int          iLen;
};

const FV_CoverAsset * FV_coverAssetById(const char * szId);

#endif /* FV_COVERASSETS_H */
