#!/bin/sh

srcdir=..
destdir=build

mkdir $destdir
mkdir $destdir/tutorial
mkdir $destdir/howto
mkdir $destdir/info
mkdir $destdir/interface
mkdir $destdir/plugins
mkdir $destdir/problems

cp $srcdir/template/style.css    $destdir/
cp $srcdir/template/AbiSwish.png $destdir/

Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: howto; active-submenu: howtables" \
	--to=$destdir/howto/howtotables.html $srcdir/howto/howtotables.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: howto; active-submenu: howdocs" \
	--to=$destdir/howto/howtodocs.html $srcdir/howto/howtodocs.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: howto; active-submenu: howlists" \
	--to=$destdir/howto/howtolists.html $srcdir/howto/howtolists.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: howto; active-submenu: howdocument" \
	--to=$destdir/howto/howtodocument.html $srcdir/howto/howtodocument.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: howto; active-submenu: howprefs" \
	--to=$destdir/howto/howtoprefs.html $srcdir/howto/howtoprefs.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: howto; active-submenu: howmailmerge" \
	--to=$destdir/howto/howtomailmerge.html $srcdir/howto/howtomailmerge.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: howto; active-submenu: howtemplate" \
	--to=$destdir/howto/howtonormaltemplate.html $srcdir/howto/howtonormaltemplate.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: howto; active-submenu: howweb" \
	--to=$destdir/howto/howtoweb.html $srcdir/howto/howtoweb.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: howto; active-submenu: howmsword" \
	--to=$destdir/howto/howtoword.html $srcdir/howto/howtoword.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: howto; active-submenu: howexphtml" \
	--to=$destdir/howto/howtoexporthtml.html $srcdir/howto/howtoexporthtml.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: howto; active-submenu: howindex" \
	--to=$destdir/howto/index.html $srcdir/howto/index.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: info; active-submenu: infindex" \
	--to=$destdir/info/index.html $srcdir/info/index.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: info; active-submenu: infformats" \
	--to=$destdir/info/infoformats.html $srcdir/info/infoformats.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: info; active-submenu: infmsdi" \
	--to=$destdir/info/infomsdi.html $srcdir/info/infomsdi.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: info; active-submenu: infsections" \
	--to=$destdir/info/infosections.html $srcdir/info/infosections.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: info; active-submenu: infsysreq" \
	--to=$destdir/info/inforequirements.html $srcdir/info/inforequirements.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: info; active-submenu: infspelling" \
	--to=$destdir/info/infospelling.html $srcdir/info/infospelling.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdbgcolor" \
	--to=$destdir/interface/dialogbackgroundcolor.html $srcdir/interface/dialogbackgroundcolor.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdbookmark" \
	--to=$destdir/interface/dialogbookmark.html $srcdir/interface/dialogbookmark.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdbreak" \
	--to=$destdir/interface/dialogbreak.html $srcdir/interface/dialogbreak.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdchgcase" \
	--to=$destdir/interface/dialogchangecase.html $srcdir/interface/dialogchangecase.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdcolumns" \
	--to=$destdir/interface/dialogcolumns.html $srcdir/interface/dialogcolumns.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intddatetime" \
	--to=$destdir/interface/dialogdateandtime.html $srcdir/interface/dialogdateandtime.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdfield" \
	--to=$destdir/interface/dialogfield.html $srcdir/interface/dialogfield.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdfind" \
	--to=$destdir/interface/dialogfind.html $srcdir/interface/dialogfind.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdfont" \
	--to=$destdir/interface/dialogfont.html $srcdir/interface/dialogfont.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdgoto" \
	--to=$destdir/interface/dialoggoto.html $srcdir/interface/dialoggoto.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdinstable" \
	--to=$destdir/interface/dialoginserttable.html $srcdir/interface/dialoginserttable.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdfmttable" \
	--to=$destdir/interface/dialogformattable.html $srcdir/interface/dialogformattable.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdmergecls" \
	--to=$destdir/interface/dialogmergecells.html $srcdir/interface/dialogmergecells.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdfootnote" \
	--to=$destdir/interface/dialogformatfootnotes.html $srcdir/interface/dialogformatfootnotes.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdhdrftr" \
	--to=$destdir/interface/dialogformatheaderfooters.html $srcdir/interface/dialogformatheaderfooters.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdhreflink" \
	--to=$destdir/interface/dialoghyperlink.html $srcdir/interface/dialoghyperlink.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdhtmlex" \
	--to=$destdir/interface/dialoghtmlexport.html $srcdir/interface/dialoghtmlexport.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdimgprops" \
	--to=$destdir/interface/dialogimageproperties.html $srcdir/interface/dialogimageproperties.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdlang" \
	--to=$destdir/interface/dialoglanguage.html $srcdir/interface/dialoglanguage.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdlists" \
	--to=$destdir/interface/dialoglists.html $srcdir/interface/dialoglists.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdmailm" \
	--to=$destdir/interface/dialogmailmerge.html $srcdir/interface/dialogmailmerge.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdmailmt" \
	--to=$destdir/interface/dialogmailmergetool.html $srcdir/interface/dialogmailmergetool.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdmarkrev" \
	--to=$destdir/interface/dialogmarkrevisions.html $srcdir/interface/dialogmarkrevisions.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdselrev" \
	--to=$destdir/interface/dialogselectrevision.html $srcdir/interface/dialogselectrevision.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdmodstyle" \
	--to=$destdir/interface/dialogmodifystyle.html $srcdir/interface/dialogmodifystyle.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdnew" \
	--to=$destdir/interface/dialognew.html $srcdir/interface/dialognew.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdnewstyle" \
	--to=$destdir/interface/dialognewstyle.html $srcdir/interface/dialognewstyle.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdopenlin" \
	--to=$destdir/interface/dialogopenlinux.html $srcdir/interface/dialogopenlinux.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdpagenos" \
	--to=$destdir/interface/dialogpagenumbers.html $srcdir/interface/dialogpagenumbers.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdpageset" \
	--to=$destdir/interface/dialogpagesetup.html $srcdir/interface/dialogpagesetup.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdpara" \
	--to=$destdir/interface/dialogparagraph.html $srcdir/interface/dialogparagraph.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdprefs" \
	--to=$destdir/interface/dialogpreferences.html $srcdir/interface/dialogpreferences.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdprint" \
	--to=$destdir/interface/dialogprint.html $srcdir/interface/dialogprint.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdprops" \
	--to=$destdir/interface/dialogproperties.html $srcdir/interface/dialogproperties.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdreplace" \
	--to=$destdir/interface/dialogreplace.html $srcdir/interface/dialogreplace.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdsavelin" \
	--to=$destdir/interface/dialogsavelinux.html $srcdir/interface/dialogsavelinux.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdscrcolor" \
	--to=$destdir/interface/dialogscreencolor.html $srcdir/interface/dialogscreencolor.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdspell" \
	--to=$destdir/interface/dialogspelling.html $srcdir/interface/dialogspelling.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdstyles" \
	--to=$destdir/interface/dialogstyles.html $srcdir/interface/dialogstyles.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdsymbol" \
	--to=$destdir/interface/dialogsymbol.html $srcdir/interface/dialogsymbol.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdtabs" \
	--to=$destdir/interface/dialogtabs.html $srcdir/interface/dialogtabs.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdviewdoc" \
	--to=$destdir/interface/dialogviewdocument.html $srcdir/interface/dialogviewdocument.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdwordcnt" \
	--to=$destdir/interface/dialogwordcount.html $srcdir/interface/dialogwordcount.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intdzoom" \
	--to=$destdir/interface/dialogzoom.html $srcdir/interface/dialogzoom.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intindex" \
	--to=$destdir/interface/index.html $srcdir/interface/index.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intwspace" \
	--to=$destdir/interface/workspace.html $srcdir/interface/workspace.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intmcontext" \
	--to=$destdir/interface/menucontextual.html $srcdir/interface/menucontextual.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intmedit" \
	--to=$destdir/interface/menuedit.html $srcdir/interface/menuedit.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intmfile" \
	--to=$destdir/interface/menufile.html $srcdir/interface/menufile.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intmformat" \
	--to=$destdir/interface/menuformat.html $srcdir/interface/menuformat.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intmhelp" \
	--to=$destdir/interface/menuhelp.html $srcdir/interface/menuhelp.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intminsert" \
	--to=$destdir/interface/menuinsert.html $srcdir/interface/menuinsert.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intmtools" \
	--to=$destdir/interface/menutools.html $srcdir/interface/menutools.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intmtable" \
	--to=$destdir/interface/menutable.html $srcdir/interface/menutable.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intmview" \
	--to=$destdir/interface/menuview.html $srcdir/interface/menuview.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intmwindow" \
	--to=$destdir/interface/menuwindow.html $srcdir/interface/menuwindow.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intrulers" \
	--to=$destdir/interface/rulers.html $srcdir/interface/rulers.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: inttextra" \
	--to=$destdir/interface/toolbarextra.html $srcdir/interface/toolbarextra.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: intttable" \
	--to=$destdir/interface/toolbartable.html $srcdir/interface/toolbartable.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: inttformat" \
	--to=$destdir/interface/toolbarformatting.html $srcdir/interface/toolbarformatting.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: interface; active-submenu: inttstandard" \
	--to=$destdir/interface/toolbarstandard.html $srcdir/interface/toolbarstandard.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: problems; active-submenu: proindex" \
	--to=$destdir/problems/index.html $srcdir/problems/index.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: problems; active-submenu: probugs" \
	--to=$destdir/problems/problemsbugs.html $srcdir/problems/problemsbugs.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: problems; active-submenu: profaq" \
	--to=$destdir/problems/problemsfaq.html $srcdir/problems/problemsfaq.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: problems; active-submenu: prohelp" \
	--to=$destdir/problems/problemshelp.html $srcdir/problems/problemshelp.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: tutorial" \
	--to=$destdir/tutorial/index.html $srcdir/tutorial/index.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: tutorial; active-submenu: tutintro" \
	--to=$destdir/tutorial/intro.html $srcdir/tutorial/intro.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: tutorial; active-submenu: tutwindow" \
	--to=$destdir/tutorial/window.html $srcdir/tutorial/window.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: ..; active-menu: plugins" \
	--to=$destdir/plugins/index.html $srcdir/plugins/index.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: .; active-menu: aboutos" \
	--to=$destdir/aboutos.html $srcdir/aboutos.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: .; active-menu: azindex" \
	--to=$destdir/azindex.html $srcdir/azindex.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: .; active-menu: fdl" \
	--to=$destdir/fdl.html $srcdir/fdl.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: .; active-menu: top; active-submenu: topindex" \
	--to=$destdir/index.html $srcdir/index.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: .; active-menu: top; active-submenu: topintro" \
	--to=$destdir/introduction.html $srcdir/introduction.abw
Abinova-2.0 --exp-props="html-template: $srcdir/template/template.html; href-prefix: .; active-menu: search" \
	--to=$destdir/search.html $srcdir/search.abw
