

EXTRA_DIST = \
	cdump/xp/cdump.py \
	rtfgen/generate-rtf.py \
	rtfgen/rtf-keywords.txt \
	rtfgen/README \
	clang-fmt.py \
	release.sh \
	changelog2html.sh \
	epub-rt-check.sh \
	rt-check.sh \
	build-macos.sh \
	build-windows-msys2.sh \
	build-gtk-prefix.sh \
	build-fuzz.sh \
	check-fuzz.sh \
	check-san.sh \
	check-valgrind.sh \
	valgrind.supp \
	fuzz-add-reproducer.sh \
	coverage.sh \
	lcov/README \
	lcov/COPYING \
	lcov/lcovrc \
	lcov/lcov \
	lcov/geninfo \
	lcov/genhtml \
	lcov/genpng \
	lcov/gendesc
