#!/bin/sh
# portguard.sh — portability leak guard (TST08, covers PORT01-07)
#
# Two checks over shipped code in src/:
#
# 1. No "/tmp" string literals. Hardcoding /tmp breaks on Windows and
#    non-standard POSIX layouts; use g_get_tmp_dir(). Test files
#    (*/t/*, *.t.cpp, src/wp/test), the vendored thirdparty/ tree and
#    the scratch build copies (fuzz-build/, san-build/) are exempt.
#
# 2. No NEW unistd-only API surface in xp code (directories named
#    "xp" under src/). The unistd calls already present are the
#    PORT01-06 backlog and live in tools/portguard-baseline.txt:
#    a finding not in the baseline fails the check, and a baseline
#    entry that no longer appears in the tree fails too — shrink the
#    baseline as the PORT tasks land, never grow it.
#
# POSIX usage is allowed by design in the portability seam and test
# tooling (exempt):
#   src/af/util/xp/ut_go_file.cpp   — the UT_go_* file helper impl
#   src/af/util/xp/ut_raii.h        — UT_ScopedFD wraps ::close
#   src/af/tf/**                    — the TF test framework
#   */t/**, *.t.cpp, src/wp/test    — tests
#
# Findings recorded per file:
#   file: #include <unistd.h>
#   file: ::name          (explicit global-namespace unistd call)
#   file: name            (unqualified call of a name no sane class
#                          uses as a member, e.g. getrandom, fsync)
#
# Usage: portguard.sh [srcdir]      exits 0 ok / 1 violations
# Regenerate the baseline ONLY after verifying every new entry is a
# known PORT-task leak:  tools/portguard.sh --write-baseline

set -u

HERE=$(cd "$(dirname "$0")" && pwd)
BASELINE="$HERE/portguard-baseline.txt"
SRCDIR=""
WRITE=0
for a in "$@"; do
	case "$a" in
		--write-baseline) WRITE=1 ;;
		*) SRCDIR="$a" ;;
	esac
done
[ -n "$SRCDIR" ] || SRCDIR=$(cd "$HERE/.." && pwd)

fail=0

# --- check 1: no /tmp literals in shipped code ----------------------

tmp_hits=$(grep -rn -e '"/tmp' -e "'/tmp" "$SRCDIR/src" \
	--include='*.cpp' --include='*.c' --include='*.h' --include='*.hpp' \
	2>/dev/null | grep -vE '/t/|\.t\.cpp|src/wp/test' || true)
if [ -n "$tmp_hits" ]; then
	echo "FAIL: /tmp literals in shipped code:" >&2
	echo "$tmp_hits" >&2
	fail=1
fi

# --- check 2: unistd-API surface in xp code --------------------------

# names that appear only in unistd.h and are implausible as member
# functions — flag unqualified calls of these anywhere in xp code
UQ_FUNCS="getrandom|getentropy|fsync|fdatasync|isatty|ttyname|readlink|symlink|getpid|getppid|getpagesize|sysconf|pathconf|fpathconf|ftruncate|usleep|pread|pwrite|chroot|daemon|fchdir|lstat|mkfifo|mknod|setuid|setgid|getuid|getgid|geteuid|getegid|chown|fchown|lockf|fork|vfork|execl|execlp|execle|execv|execvp|getlogin|gethostname|sethostname|getgroups|umask|setpgid|setsid|pause|nice|chdir|rmdir|getcwd|confstr|tcgetpgrp|tcsetpgrp|syncfs|getdtablesize"

# names that collide with common member functions — only flag the
# explicit global-namespace form ::name(
G_FUNCS="open|close|read|write|lseek|unlink|stat|fstat|chmod|fchmod|access|rename|dup|dup2|pipe|sleep|link|sync|truncate|fdopen|alarm|mkdir|socket|accept|bind|listen|connect|send|recv|wait|kill|mmap|munmap"

xp_dirs=$(find "$SRCDIR/src" -type d -name xp \
	! -path '*/fuzz-build/*' ! -path '*/san-build/*' 2>/dev/null)
xp_files=$(find $xp_dirs -maxdepth 1 -type f \
	\( -name '*.cpp' -o -name '*.c' -o -name '*.h' -o -name '*.hpp' \) \
	| grep -vE '/t/|\.t\.cpp' \
	| grep -vE 'src/af/util/xp/ut_go_file\.cpp|src/af/util/xp/ut_raii\.h|src/af/tf/')

current_file=$(mktemp)
trap 'rm -f "$current_file" "$bas_file"' EXIT
bas_file=$(mktemp)

for f in $xp_files; do
	rel=${f#$SRCDIR/}
	if grep -qE '#[[:space:]]*include[[:space:]]*<unistd\.h>' "$f" 2>/dev/null; then
		echo "$rel: #include <unistd.h>"
	fi
	grep -oE '(^|[^A-Za-z0-9_:.>])::('"$UQ_FUNCS|$G_FUNCS"')[[:space:]]*\(' "$f" 2>/dev/null \
		| sed -E 's/^.*::([A-Za-z0-9_]+)[[:space:]]*\(.*$/::\1/' \
		| sort -u | sed "s|^|$rel: |"
	grep -oE '(^|[^A-Za-z0-9_:.>])('"$UQ_FUNCS"')[[:space:]]*\(' "$f" 2>/dev/null \
		| sed -E 's/^[^A-Za-z0-9_:.>]?//; s/[[:space:]]*\(.*$//' \
		| sort -u | sed "s|^|$rel: |"
done | sort -u > "$current_file"

if [ "$WRITE" -eq 1 ]; then
	{
		echo '# portguard baseline — known unistd-only API leaks in xp code.'
		echo '# Generated by tools/portguard.sh --write-baseline. These are the'
		echo '# PORT01-06 backlog; a PORT task must REMOVE its entries here when'
		echo '# it removes the call sites (a stale entry fails the guard).'
		cat "$current_file"
	} > "$BASELINE"
	echo "portguard: wrote $BASELINE" >&2
	exit 0
fi

grep -vE '^[[:space:]]*#|^[[:space:]]*$' "$BASELINE" 2>/dev/null | sort > "$bas_file"

new=$(comm -13 "$bas_file" "$current_file")
stale=$(comm -23 "$bas_file" "$current_file")

if [ -n "$new" ]; then
	echo "FAIL: new unistd-only API in xp code (not in baseline):" >&2
	echo "$new" >&2
	fail=1
fi
if [ -n "$stale" ]; then
	echo "FAIL: stale baseline entries — remove them from $BASELINE:" >&2
	echo "$stale" >&2
	fail=1
fi

if [ "$fail" -eq 0 ]; then
	n=$(grep -c . "$bas_file" 2>/dev/null || echo 0)
	echo "portguard: OK — no /tmp literals; unistd surface matches baseline ($n known PORT-task leaks)"
fi
exit "$fail"
