
noinst_LTLIBRARIES = libev.la

AM_CPPFLAGS = \
	$(WP_CPPFLAGS) \
	$(AF_CPPFLAGS)

libev_la_SOURCES = \
	xp/ev_EditBinding.cpp \
	xp/ev_EditBinding.h \
	xp/ev_EditBits.h \
	xp/ev_EditEventMapper.cpp \
	xp/ev_EditEventMapper.h \
	xp/ev_EditMethod.cpp \
	xp/ev_EditMethod.h \
	xp/ev_Keyboard.cpp \
	xp/ev_Keyboard.h \
	xp/ev_Menu_Actions.cpp \
	xp/ev_Menu_Actions.h \
	xp/ev_Menu.cpp \
	xp/ev_Menu.h \
	xp/ev_Menu_Labels.cpp \
	xp/ev_Menu_Labels.h \
	xp/ev_Menu_Layouts.cpp \
	xp/ev_Menu_Layouts.h \
	xp/ev_Mouse.cpp \
	xp/ev_Mouse.h \
	xp/ev_MouseListener.h \
	xp/ev_NamedVirtualKey.cpp \
	xp/ev_NamedVirtualKey.h \
	xp/ev_Toolbar_Actions.cpp \
	xp/ev_Toolbar_Actions.h \
	xp/ev_Toolbar_Control.cpp \
	xp/ev_Toolbar_Control.h \
	xp/ev_Toolbar.cpp \
	xp/ev_Toolbar.h \
	xp/ev_Toolbar_Labels.cpp \
	xp/ev_Toolbar_Labels.h \
	xp/ev_Toolbar_Layouts.cpp \
	xp/ev_Toolbar_Layouts.h

libev_la_SOURCES += \
	gtk/ev_UnixFontCombo.cpp \
	gtk/ev_UnixFontCombo.h \
	gtk/ev_UnixKeyboard.cpp \
	gtk/ev_UnixKeyboard.h \
	gtk/ev_UnixKeysym2ucs.cpp \
	gtk/ev_UnixKeysym2ucs.h \
	gtk/ev_UnixMenuBar.h \
	gtk/ev_UnixMenu.cpp \
	gtk/ev_UnixMenu.h \
	gtk/ev_UnixMenuPopup.h \
	gtk/ev_UnixMouse.cpp \
	gtk/ev_UnixMouse.h \
	gtk/ev_UnixToolbar.cpp \
	gtk/ev_UnixToolbar.h \
	gtk/ev_UnixToolbar_ViewListener.cpp \
	gtk/ev_UnixToolbar_ViewListener.h



